#!/usr/bin/env python3

import argparse
import game
from pathlib import Path
from definitions import ROOT_DIR


parser = argparse.ArgumentParser(description='Investigate any clues or locations. Clues are hidden files that start with \'.\'')
parser.add_argument('-l', '--location', help='Investigate a location i.e. investigate -l \"Madeup Avenue 10\"')
parser.add_argument('-c', '--clue', help='Investigate a file that starts with \'.\'')
parser.add_argument('-p', '--person', help='Investigate a person\'s background')
args = parser.parse_args()

def invest_evidence(game_state, clue):
    if clue == '.wallpaper':
        with open(str(Path(ROOT_DIR) / '.Secret' / 'Dialogue' / 'wallpaper.txt'), 'r') as fin:
            print(fin.read())
    elif clue == '.phone':
        print('(A lot of shinies on that Pokemon Go account...)')
    else:
        print('You can\'t perform this action!')

def invest_location(game_state, loc):  
    if Path().absolute().name != 'Streets': 
        print('You can\'t even go to this location! Go to the Streets first!')
        return

    if game_state == game.GameState.INTRO:
        print('Why are you even trying to visit houses?')
        return

    if loc == 'College Avenue 34':
        if game_state == game.GameState.ASSIGNMENT:
            print('Click.')
            print('You have now unlocked Andre_House')
        else:
            print('You\'ve already investigated this house')
    else:
        print('Woah...did not mean to see THAT') 

if (args.location):
    game.progress(game.Action.INVESTIGATE, args.location)
    invest_location(game.game_state, args.location)
    
if (args.clue):
    game.progress(game.Action.INVESTIGATE, args.clue)
    invest_evidence(game.game_state, args.clue)
    
if (args.person):
    print('Like we have the budget to perform a background check...')
